class Intervals{
  final List<double> temps;
  final List<String> conditions;
  final List<String> times;

  Intervals({
    required this.temps,
    required this.conditions,
    required this.times
  });

  factory Intervals.fromJson(Map<String, dynamic> json) {
    return Intervals(
      temps: [json['list'][0]['main']['temp'].toDouble(),
        json['list'][1]['main']['temp'].toDouble(),
        json['list'][2]['main']['temp'].toDouble(),
        json['list'][3]['main']['temp'].toDouble(),
        json['list'][4]['main']['temp'].toDouble(),
        json['list'][5]['main']['temp'].toDouble(),
        json['list'][6]['main']['temp'].toDouble(),
        json['list'][7]['main']['temp'].toDouble(),
        json['list'][8]['main']['temp'].toDouble(),
        json['list'][9]['main']['temp'].toDouble(),
        json['list'][10]['main']['temp'].toDouble(),
        json['list'][11]['main']['temp'].toDouble(),
        json['list'][12]['main']['temp'].toDouble(),
        json['list'][13]['main']['temp'].toDouble(),
        json['list'][14]['main']['temp'].toDouble(),
        json['list'][15]['main']['temp'].toDouble(),
        json['list'][16]['main']['temp'].toDouble(),
        json['list'][17]['main']['temp'].toDouble(),
        json['list'][18]['main']['temp'].toDouble(),
        json['list'][19]['main']['temp'].toDouble(),
        json['list'][20]['main']['temp'].toDouble(),
        json['list'][21]['main']['temp'].toDouble(),
        json['list'][22]['main']['temp'].toDouble(),
        json['list'][23]['main']['temp'].toDouble(),
        json['list'][24]['main']['temp'].toDouble(),
        json['list'][25]['main']['temp'].toDouble(),
        json['list'][26]['main']['temp'].toDouble(),
        json['list'][27]['main']['temp'].toDouble(),
        json['list'][28]['main']['temp'].toDouble(),
        json['list'][29]['main']['temp'].toDouble(),
        json['list'][30]['main']['temp'].toDouble(),
        json['list'][31]['main']['temp'].toDouble(),
        json['list'][32]['main']['temp'].toDouble(),
        json['list'][33]['main']['temp'].toDouble(),
        json['list'][34]['main']['temp'].toDouble(),
        json['list'][35]['main']['temp'].toDouble(),
        json['list'][36]['main']['temp'].toDouble(),
        json['list'][37]['main']['temp'].toDouble(),
        json['list'][38]['main']['temp'].toDouble(),
        json['list'][39]['main']['temp'].toDouble(),
      ],
      conditions: [json['list'][0]['weather'][0]['main'],
        json['list'][1]['weather'][0]['main'],
        json['list'][2]['weather'][0]['main'],
        json['list'][3]['weather'][0]['main'],
        json['list'][4]['weather'][0]['main'],
        json['list'][5]['weather'][0]['main'],
        json['list'][6]['weather'][0]['main'],
        json['list'][7]['weather'][0]['main'],
        json['list'][8]['weather'][0]['main'],
        json['list'][9]['weather'][0]['main'],
        json['list'][10]['weather'][0]['main'],
        json['list'][11]['weather'][0]['main'],
        json['list'][12]['weather'][0]['main'],
        json['list'][13]['weather'][0]['main'],
        json['list'][14]['weather'][0]['main'],
        json['list'][15]['weather'][0]['main'],
        json['list'][16]['weather'][0]['main'],
        json['list'][17]['weather'][0]['main'],
        json['list'][18]['weather'][0]['main'],
        json['list'][19]['weather'][0]['main'],
        json['list'][20]['weather'][0]['main'],
        json['list'][21]['weather'][0]['main'],
        json['list'][22]['weather'][0]['main'],
        json['list'][23]['weather'][0]['main'],
        json['list'][24]['weather'][0]['main'],
        json['list'][25]['weather'][0]['main'],
        json['list'][26]['weather'][0]['main'],
        json['list'][27]['weather'][0]['main'],
        json['list'][28]['weather'][0]['main'],
        json['list'][29]['weather'][0]['main'],
        json['list'][30]['weather'][0]['main'],
        json['list'][31]['weather'][0]['main'],
        json['list'][32]['weather'][0]['main'],
        json['list'][33]['weather'][0]['main'],
        json['list'][34]['weather'][0]['main'],
        json['list'][35]['weather'][0]['main'],
        json['list'][36]['weather'][0]['main'],
        json['list'][37]['weather'][0]['main'],
        json['list'][38]['weather'][0]['main'],
        json['list'][39]['weather'][0]['main']
      ],
      times: [json['list'][0]['dt_txt'],
        json['list'][1]['dt_txt'],
        json['list'][2]['dt_txt'],
        json['list'][3]['dt_txt'],
        json['list'][4]['dt_txt'],
        json['list'][5]['dt_txt'],
        json['list'][6]['dt_txt'],
        json['list'][7]['dt_txt'],
        json['list'][8]['dt_txt'],
        json['list'][9]['dt_txt'],
        json['list'][10]['dt_txt'],
        json['list'][11]['dt_txt'],
        json['list'][12]['dt_txt'],
        json['list'][13]['dt_txt'],
        json['list'][14]['dt_txt'],
        json['list'][15]['dt_txt'],
        json['list'][16]['dt_txt'],
        json['list'][17]['dt_txt'],
        json['list'][18]['dt_txt'],
        json['list'][19]['dt_txt'],
        json['list'][20]['dt_txt'],
        json['list'][21]['dt_txt'],
        json['list'][22]['dt_txt'],
        json['list'][23]['dt_txt'],
        json['list'][24]['dt_txt'],
        json['list'][25]['dt_txt'],
        json['list'][26]['dt_txt'],
        json['list'][27]['dt_txt'],
        json['list'][28]['dt_txt'],
        json['list'][29]['dt_txt'],
        json['list'][30]['dt_txt'],
        json['list'][31]['dt_txt'],
        json['list'][32]['dt_txt'],
        json['list'][33]['dt_txt'],
        json['list'][34]['dt_txt'],
        json['list'][35]['dt_txt'],
        json['list'][36]['dt_txt'],
        json['list'][37]['dt_txt'],
        json['list'][38]['dt_txt'],
        json['list'][39]['dt_txt'],
      ]
    );
  }
}